# Generated by Django 3.2.4 on 2021-06-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejproxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='ej_cookie',
            new_name='ej_sid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ej_srvctl_cookie',
            new_name='ej_srvctl_sid',
        ),
    ]
